blank_issues_enabled: true
contact_links:
  - name: Discussions and support
    url: https://github.com/GT-610/csgo-gc/issues
    about: For general discussion, use blank issue template. DO NOT report bugs with blank issue, or it will be closed directly.
